name: apiato
recipe: laravel
config:
  webroot: public
  database: mysql:8.0
  cache: redis
  php: '8.0'
services:
  database:
    portforward: 3308
  cache:
    portforward: 6380
  appserver:
    xdebug: true
tooling:
  cache:
    service: appserver
    cmd: php artisan config:cache
  clear-log:
    service: appserver
    cmd: cd ./storage/logs/ && rm -rf ./*.log   && touch laravel.log debugger.log cron.log   && echo 'done'
  tinker:
    service: appserver
    cmd: php artisan tinker
  fresh:
    service: appserver
    cmd: php artisan migrate:fresh
  fresh-seed:
    service: appserver
    cmd: php artisan migrate:fresh --seed
  work:
    service: appserver
    cmd: php artisan queue:work
  m:
    service: appserver
    cmd: php artisan migrate
  gc:
    service: appserver
    cmd: php artisan apiato:generate:container
  gm:
    service: appserver
    cmd: php artisan apiato:generate:migration
proxy:
  appserver:
    - apiato.lndo.site
    - api.apiato.lndo.site
    - admin.apiato.lndo.site
